# This is an example configuration that loads the "Kitchen" scene from the
# local MoveIt warehouse and benchmarks the "panda_arm" group in the Pick1
# query using the Start1 initial state (all pre-stored in the local warehouse)

# Three different planners from OMPL are run a total of 50 times each, with a
# maximum of 10 seconds per run.  Output is stored in the /tmp/moveit_benchmarks directory.
warehouse:
    host: /root/ws_moveit/src/ur5e_cutter_moveit_config/config/ur_benchmarks.sqlite
    port: 33829
    scene_name: tree1     # Required
parameters:
    name: CutBranch1
    runs: 50
    group: ur5e_arm       # Required
    timeout: 10.0
    output_directory: /tmp/moveit_benchmarks/
    queries: Motion Plan Request 0
    start_states: ur5e_state_000
planning_pipelines:
    pipelines: [pipeline1]
    pipeline1:
        name: ompl
        planners:
            - RRTkConfigDefault
            - RRTConnectkConfigDefault
            - RRTstarkConfigDefault
            - TRRTkConfigDefault
            - PRMkConfigDefault
            - PRMstarkConfigDefault
            - FMTkConfigDefault
            - BFMTkConfigDefault
            - BiTRRTkConfigDefault
            - LBTRRTkConfigDefault
            - LazyPRMkConfigDefault
            - LazyPRMstarkConfigDefault
            - geometric:RRT
            - geometric:RRTConnect
            - geometric:RRTstar
            - geometric:BiTRRT
            - geometric:FMT
            - geometric:BFMT
            - geometric:PRM
            - geometric:PRMstar
